[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = ["cd app && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd app && npm run build"]

[phases.setup]
aptPkgs = ["python3-dev", "python3-pip", "gcc"]

[start]
cmd = "cd app && python app.py"
